### ISSUE TITLE
export with match project crs fails with rasters to be exported

### ISSUE THREAD

**Issue by riccardoklinger** [Geolicious/qgis2leaf#180]
this was the error:
Fehler bei der Ausführung von Python-Code:

Traceback (most recent call last):
  File "C:/Users/ricckli/.qgis2/python/plugins\qgis2leaf\qgis2leafdialog.py", line 296, in export2leaf
    qgis2leaf_exec(self.outFileName, self.basemapName, self.basemapMeta, self.basemapAddress, self.width, self.height, self.extent, self.full_screen, self.layer_list, self.visible, self.opacity, self.encode2JSON,self.createcluster, self.webpage_name, self.webmap_head,self.webmap_subhead, self.legend,self.locate,self.address, self.precision, self.labels, self.labelshover, self.matchCRS)
  File "C:/Users/ricckli/.qgis2/python/plugins\qgis2leaf\qgis2leaf_exec.py", line 498, in qgis2leaf_exec
    processing.runalg("gdalogr:warpreproject",str(in_raster),str(i.crs().authid()),"EPSG:4326",0,1,"",prov_raster)
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins\processing\tools\general.py", line 71, in runalg
    alg = Processing.runAlgorithm(algOrName, None, *args)
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins\processing\core\Processing.py", line 303, in runAlgorithm
    processing.alghelp(algOrName)
  File "C:/PROGRA~1/QGISBR~1/apps/qgis/./python/plugins\processing\tools\general.py", line 64, in alghelp
    print str(alg)
IOError: [Errno 9] Bad file descriptor

this was the selection screen in th plugin:
![2014-12-16 19_11_51-find out more about greenshot _ sourceforge net](https://cloud.githubusercontent.com/assets/7377897/5459037/943cc218-8557-11e4-9c46-9ca6d1d1df8c.png)

**Comment by tomchadwin** [comment]
I can't recreate this. Your selection does give me an error, but it's relating to the basemaps (I'll open a new issue for that), not to the raster. I don't get your error. Are you still getting it?

**Comment by riccardoklinger** [comment]
still throwing an error:
![error_gui](https://cloud.githubusercontent.com/assets/7377897/7148904/cd3243e6-e307-11e4-977b-e4f26a2e344e.png)

An error has occured while executing Python code:


Traceback (most recent call last):
  File "/home/ricckli/.qgis2/python/plugins/qgis2leaf/qgis2leafdialog.py", line 297, in export2leaf
    qgis2leaf_exec(self.outFileName, self.basemapName, self.basemapMeta, self.basemapAddress, self.width, self.height, self.extent, self.full_screen, self.layer_list, self.visible, self.opacity, self.encode2JSON,self.createcluster, self.webpage_name, self.webmap_head,self.webmap_subhead, self.legend,self.locate,self.address, self.precision, self.labels, self.labelshover, self.matchCRS, self.selected)
  File "/home/ricckli/.qgis2/python/plugins/qgis2leaf/qgis2leaf_exec.py", line 71, in qgis2leaf_exec
    if matchCRS == True and canvas.mapRenderer().destinationCrs().authid() != 'EPSG:4326':
UnboundLocalError: local variable 'canvas' referenced before assignment

**Comment by riccardoklinger** [comment]
error was easy to solve so I assigned the canvas variable.
