### ISSUE TITLE
Error when using SVG markers

### ISSUE THREAD

**Issue by rajanski** [Geolicious/qgis2leaf#196]
Traceback (most recent call last):
  File "/home/work/.qgis2/python/plugins/qgis2leaf/qgis2leafdialog.py", line 295, in export2leaf
    qgis2leaf_exec(self.outFileName, self.basemapName, self.basemapMeta, self.basemapAddress, self.width, self.height, self.extent, self.full_screen, self.layer_list, self.visible, self.opacity, self.encode2JSON,self.createcluster, self.webpage_name, self.webmap_head,self.webmap_subhead, self.legend,self.locate,self.address, self.precision, self.labels, self.labelshover)
  File "/home/work/.qgis2/python/plugins/qgis2leaf/qgis2leaf_exec.py", line 222, in qgis2leaf_exec
    if str(i.rendererV2().symbol().symbolLayer(0).borderColor().name()):
AttributeError: 'QgsFontMarkerSymbolLayerV2' object has no attribute 'borderColor'

**Comment by bobintornado** [comment]
same issue here.

**Comment by tomchadwin** [comment]
At the moment, I believe, custom symbols in QGIS are not supported. However, you can use the field icon_exp in your table to specify a custom icon - see the readme or help tab for details.

**Comment by tomchadwin** [comment]
To clarify - you will have to remove the SVG symbol in QGIS, reverting to ordinary point symbology. That should prevent the plugin from crashing. Then use icon_exp to specify your custom symbol.

**Comment by stefancive** [comment]
This problem dosen´t appear when you use rule based styling.
