### ISSUE TITLE
Error with brushStyle

### ISSUE THREAD

**Issue by pcav** [Geolicious/qgis2leaf#216]
I'm getting this error with a simple project:

An error has occured while executing Python code:

Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/qgis2leaf/qgis2leafdialog.py", line 297, in export2leaf
    qgis2leaf_exec(self.outFileName, self.basemapName, self.basemapMeta, self.basemapAddress, self.width, self.height, self.extent, self.full_screen, self.layer_list, self.visible, self.opacity, self.encode2JSON,self.createcluster, self.webpage_name, self.webmap_head,self.webmap_subhead, self.legend,self.locate,self.address, self.precision, self.labels, self.labelshover, self.matchCRS, self.selected)
  File "/home/paolo/.qgis2/python/plugins/qgis2leaf/qgis2leaf_exec.py", line 288, in qgis2leaf_exec
    if i.rendererV2().symbol().symbolLayer(0).brushStyle() == 0:
AttributeError: 'QgsSimpleLineSymbolLayerV2' object has no attribute 'brushStyle'

**Comment by tomchadwin** [comment]
Can you describe the layer style/symbology?

**Comment by pcav** [comment]
Here is a simple project:

<!DOCTYPE qgis PUBLIC 'http://mrcc.com/qgis.dtd' 'SYSTEM'>
<qgis projectname="" version="2.8.1-Wien">
  <title></title>
  <layer-tree-group expanded="1" checked="Qt::Checked" name="">
    <customproperties/>
    <layer-tree-layer expanded="1" checked="Qt::Checked" id="Province20150325102114484" name="Province">
      <customproperties/>
    </layer-tree-layer>
  </layer-tree-group>
  <relations/>
  <mapcanvas>
    <units>meters</units>
    <extent>
      <xmin>1547220.20286378916352987</xmin>
      <ymin>4665973.563795973546803</ymin>
      <xmax>1779217.70286974590271711</xmax>
      <ymax>4933125.06380751263350248</ymax>
    </extent>
    <rotation>0</rotation>
    <projections>1</projections>
    <destinationsrs>
      <spatialrefsys>
        <proj4>+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=1500000 +y_0=0 +ellps=intl +towgs84=-104.1,-49.1,-9.9,0.971,-2.917,0.714,-11.68 +units=m +no_defs</proj4>
        <srsid>968</srsid>
        <srid>3003</srid>
        <authid>EPSG:3003</authid>
        <description>Monte Mario / Italy zone 1</description>
        <projectionacronym>tmerc</projectionacronym>
        <ellipsoidacronym>intl</ellipsoidacronym>
        <geographicflag>false</geographicflag>
      </spatialrefsys>
    </destinationsrs>
    <layer_coordinate_transform_info>
      <layer_coordinate_transform destAuthId="EPSG:3003" srcAuthId="EPSG:3003" srcDatumTransform="-1" destDatumTransform="-1" layerid="Province20150325102114484"/>
      <layer_coordinate_transform destAuthId="EPSG:3003" srcAuthId="EPSG:102091" srcDatumTransform="-1" destDatumTransform="-1" layerid="srtm_90m20150325081032958"/>
    </layer_coordinate_transform_info>
  </mapcanvas>
  <visibility-presets/>
  <layer-tree-canvas>
    <custom-order enabled="0">
      <item>Province20150325102114484</item>
    </custom-order>
  </layer-tree-canvas>
  <legend updateDrawingOrder="true">
    <legendlayer drawingOrder="-1" open="true" checked="Qt::Checked" name="Province" showFeatureCount="0">
      <filegroup open="true" hidden="false">
        <legendlayerfile isInOverview="0" layerid="Province20150325102114484" visible="1"/>
      </filegroup>
    </legendlayer>
  </legend>
  <projectlayers layercount="1">
    <maplayer minimumScale="-4.65661e-10" maximumScale="1e+08" simplifyDrawingHints="1" minLabelScale="0" maxLabelScale="1e+08" simplifyDrawingTol="1" geometry="Polygon" simplifyMaxScale="1" type="vector" hasScaleBasedVisibilityFlag="0" simplifyLocal="1" scaleBasedLabelVisibilityFlag="0">
      <id>Province20150325102114484</id>
      <datasource>../../ecdl_gis/SampleTestQGIS/Dati QGIS 1.7.4/dati/Province.shp</datasource>
      <title></title>
      <abstract></abstract>
      <keywordList>
        <value></value>
      </keywordList>
      <layername>Province</layername>
      <srs>
        <spatialrefsys>
          <proj4>+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=1500000 +y_0=0 +ellps=intl +towgs84=-104.1,-49.1,-9.9,0.971,-2.917,0.714,-11.68 +units=m +no_defs</proj4>
          <srsid>968</srsid>
          <srid>3003</srid>
          <authid>EPSG:3003</authid>
          <description>Monte Mario / Italy zone 1</description>
          <projectionacronym>tmerc</projectionacronym>
          <ellipsoidacronym>intl</ellipsoidacronym>
          <geographicflag>false</geographicflag>
        </spatialrefsys>
      </srs>
      <provider encoding="windows-1252">ogr</provider>
      <previewExpression></previewExpression>
      <vectorjoins/>
      <expressionfields/>
      <map-layer-style-manager current="">
        <map-layer-style name=""/>
      </map-layer-style-manager>
      <edittypes>
        <edittype widgetv2type="TextEdit" name="cat">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
        <edittype widgetv2type="TextEdit" name="AREA">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
        <edittype widgetv2type="TextEdit" name="PERIMETER">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
        <edittype widgetv2type="TextEdit" name="PROVINCIA">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
        <edittype widgetv2type="TextEdit" name="ETTARI">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
        <edittype widgetv2type="TextEdit" name="area2">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
        <edittype widgetv2type="TextEdit" name="area_int">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
      </edittypes>
      <renderer-v2 symbollevels="0" type="singleSymbol">
        <symbols>
          <symbol alpha="1" type="fill" name="0">
            <layer pass="0" class="SimpleLine" locked="0">
              <prop k="capstyle" v="square"/>
              <prop k="customdash" v="5;2"/>
              <prop k="customdash_map_unit_scale" v="0,0"/>
              <prop k="customdash_unit" v="MM"/>
              <prop k="draw_inside_polygon" v="0"/>
              <prop k="joinstyle" v="bevel"/>
              <prop k="line_color" v="128,152,72,255"/>
              <prop k="line_style" v="dot"/>
              <prop k="line_width" v="1.46"/>
              <prop k="line_width_unit" v="MM"/>
              <prop k="offset" v="0"/>
              <prop k="offset_map_unit_scale" v="0,0"/>
              <prop k="offset_unit" v="MM"/>
              <prop k="use_custom_dash" v="0"/>
              <prop k="width_map_unit_scale" v="0,0"/>
            </layer>
          </symbol>
        </symbols>
        <rotation/>
        <sizescale scalemethod="area"/>
      </renderer-v2>
      <customproperties>
        <property key="labeling" value="pal"/>
        <property key="labeling/addDirectionSymbol" value="false"/>
        <property key="labeling/angleOffset" value="0"/>
        <property key="labeling/blendMode" value="0"/>
        <property key="labeling/bufferBlendMode" value="0"/>
        <property key="labeling/bufferColorA" value="255"/>
        <property key="labeling/bufferColorB" value="255"/>
        <property key="labeling/bufferColorG" value="255"/>
        <property key="labeling/bufferColorR" value="255"/>
        <property key="labeling/bufferDraw" value="true"/>
        <property key="labeling/bufferJoinStyle" value="64"/>
        <property key="labeling/bufferNoFill" value="false"/>
        <property key="labeling/bufferSize" value="1"/>
        <property key="labeling/bufferSizeInMapUnits" value="false"/>
        <property key="labeling/bufferSizeMapUnitMaxScale" value="0"/>
        <property key="labeling/bufferSizeMapUnitMinScale" value="0"/>
        <property key="labeling/bufferTransp" value="0"/>
        <property key="labeling/centroidInside" value="false"/>
        <property key="labeling/centroidWhole" value="false"/>
        <property key="labeling/decimals" value="3"/>
        <property key="labeling/displayAll" value="false"/>
        <property key="labeling/dist" value="0"/>
        <property key="labeling/distInMapUnits" value="false"/>
        <property key="labeling/distMapUnitMaxScale" value="0"/>
        <property key="labeling/distMapUnitMinScale" value="0"/>
        <property key="labeling/enabled" value="true"/>
        <property key="labeling/fieldName" value="PROVINCIA"/>
        <property key="labeling/fontBold" value="false"/>
        <property key="labeling/fontCapitals" value="0"/>
        <property key="labeling/fontFamily" value="Cantarell"/>
        <property key="labeling/fontItalic" value="false"/>
        <property key="labeling/fontLetterSpacing" value="0"/>
        <property key="labeling/fontLimitPixelSize" value="false"/>
        <property key="labeling/fontMaxPixelSize" value="10000"/>
        <property key="labeling/fontMinPixelSize" value="3"/>
        <property key="labeling/fontSize" value="11"/>
        <property key="labeling/fontSizeInMapUnits" value="false"/>
        <property key="labeling/fontSizeMapUnitMaxScale" value="0"/>
        <property key="labeling/fontSizeMapUnitMinScale" value="0"/>
        <property key="labeling/fontStrikeout" value="false"/>
        <property key="labeling/fontUnderline" value="false"/>
        <property key="labeling/fontWeight" value="50"/>
        <property key="labeling/fontWordSpacing" value="0"/>
        <property key="labeling/formatNumbers" value="false"/>
        <property key="labeling/isExpression" value="false"/>
        <property key="labeling/labelOffsetInMapUnits" value="true"/>
        <property key="labeling/labelOffsetMapUnitMaxScale" value="0"/>
        <property key="labeling/labelOffsetMapUnitMinScale" value="0"/>
        <property key="labeling/labelPerPart" value="false"/>
        <property key="labeling/leftDirectionSymbol" value="&lt;"/>
        <property key="labeling/limitNumLabels" value="false"/>
        <property key="labeling/maxCurvedCharAngleIn" value="20"/>
        <property key="labeling/maxCurvedCharAngleOut" value="-20"/>
        <property key="labeling/maxNumLabels" value="2000"/>
        <property key="labeling/mergeLines" value="false"/>
        <property key="labeling/minFeatureSize" value="0"/>
        <property key="labeling/multilineAlign" value="0"/>
        <property key="labeling/multilineHeight" value="1"/>
        <property key="labeling/namedStyle" value="Regular"/>
        <property key="labeling/obstacle" value="true"/>
        <property key="labeling/placeDirectionSymbol" value="0"/>
        <property key="labeling/placement" value="1"/>
        <property key="labeling/placementFlags" value="0"/>
        <property key="labeling/plussign" value="false"/>
        <property key="labeling/preserveRotation" value="true"/>
        <property key="labeling/previewBkgrdColor" value="#ffffff"/>
        <property key="labeling/priority" value="5"/>
        <property key="labeling/quadOffset" value="4"/>
        <property key="labeling/repeatDistance" value="0"/>
        <property key="labeling/repeatDistanceMapUnitMaxScale" value="0"/>
        <property key="labeling/repeatDistanceMapUnitMinScale" value="0"/>
        <property key="labeling/repeatDistanceUnit" value="1"/>
        <property key="labeling/reverseDirectionSymbol" value="false"/>
        <property key="labeling/rightDirectionSymbol" value=">"/>
        <property key="labeling/scaleMax" value="10000000"/>
        <property key="labeling/scaleMin" value="1"/>
        <property key="labeling/scaleVisibility" value="false"/>
        <property key="labeling/shadowBlendMode" value="6"/>
        <property key="labeling/shadowColorB" value="0"/>
        <property key="labeling/shadowColorG" value="0"/>
        <property key="labeling/shadowColorR" value="0"/>
        <property key="labeling/shadowDraw" value="false"/>
        <property key="labeling/shadowOffsetAngle" value="135"/>
        <property key="labeling/shadowOffsetDist" value="1"/>
        <property key="labeling/shadowOffsetGlobal" value="true"/>
        <property key="labeling/shadowOffsetMapUnitMaxScale" value="0"/>
        <property key="labeling/shadowOffsetMapUnitMinScale" value="0"/>
        <property key="labeling/shadowOffsetUnits" value="1"/>
        <property key="labeling/shadowRadius" value="1.5"/>
        <property key="labeling/shadowRadiusAlphaOnly" value="false"/>
        <property key="labeling/shadowRadiusMapUnitMaxScale" value="0"/>
        <property key="labeling/shadowRadiusMapUnitMinScale" value="0"/>
        <property key="labeling/shadowRadiusUnits" value="1"/>
        <property key="labeling/shadowScale" value="100"/>
        <property key="labeling/shadowTransparency" value="30"/>
        <property key="labeling/shadowUnder" value="0"/>
        <property key="labeling/shapeBlendMode" value="0"/>
        <property key="labeling/shapeBorderColorA" value="255"/>
        <property key="labeling/shapeBorderColorB" value="128"/>
        <property key="labeling/shapeBorderColorG" value="128"/>
        <property key="labeling/shapeBorderColorR" value="128"/>
        <property key="labeling/shapeBorderWidth" value="0"/>
        <property key="labeling/shapeBorderWidthMapUnitMaxScale" value="0"/>
        <property key="labeling/shapeBorderWidthMapUnitMinScale" value="0"/>
        <property key="labeling/shapeBorderWidthUnits" value="1"/>
        <property key="labeling/shapeDraw" value="false"/>
        <property key="labeling/shapeFillColorA" value="255"/>
        <property key="labeling/shapeFillColorB" value="255"/>
        <property key="labeling/shapeFillColorG" value="255"/>
        <property key="labeling/shapeFillColorR" value="255"/>
        <property key="labeling/shapeJoinStyle" value="64"/>
        <property key="labeling/shapeOffsetMapUnitMaxScale" value="0"/>
        <property key="labeling/shapeOffsetMapUnitMinScale" value="0"/>
        <property key="labeling/shapeOffsetUnits" value="1"/>
        <property key="labeling/shapeOffsetX" value="0"/>
        <property key="labeling/shapeOffsetY" value="0"/>
        <property key="labeling/shapeRadiiMapUnitMaxScale" value="0"/>
        <property key="labeling/shapeRadiiMapUnitMinScale" value="0"/>
        <property key="labeling/shapeRadiiUnits" value="1"/>
        <property key="labeling/shapeRadiiX" value="0"/>
        <property key="labeling/shapeRadiiY" value="0"/>
        <property key="labeling/shapeRotation" value="0"/>
        <property key="labeling/shapeRotationType" value="0"/>
        <property key="labeling/shapeSVGFile" value=""/>
        <property key="labeling/shapeSizeMapUnitMaxScale" value="0"/>
        <property key="labeling/shapeSizeMapUnitMinScale" value="0"/>
        <property key="labeling/shapeSizeType" value="0"/>
        <property key="labeling/shapeSizeUnits" value="1"/>
        <property key="labeling/shapeSizeX" value="0"/>
        <property key="labeling/shapeSizeY" value="0"/>
        <property key="labeling/shapeTransparency" value="0"/>
        <property key="labeling/shapeType" value="0"/>
        <property key="labeling/textColorA" value="255"/>
        <property key="labeling/textColorB" value="0"/>
        <property key="labeling/textColorG" value="0"/>
        <property key="labeling/textColorR" value="0"/>
        <property key="labeling/textTransp" value="0"/>
        <property key="labeling/upsidedownLabels" value="0"/>
        <property key="labeling/wrapChar" value=""/>
        <property key="labeling/xOffset" value="0"/>
        <property key="labeling/yOffset" value="0"/>
      </customproperties>
      <blendMode>0</blendMode>
      <featureBlendMode>0</featureBlendMode>
      <layerTransparency>0</layerTransparency>
      <displayfield>cat</displayfield>
      <label>0</label>
      <labelattributes>
        <label fieldname="" text="Etichetta"/>
        <family fieldname="" name="Cantarell"/>
        <size fieldname="" units="pt" value="12"/>
        <bold fieldname="" on="0"/>
        <italic fieldname="" on="0"/>
        <underline fieldname="" on="0"/>
        <strikeout fieldname="" on="0"/>
        <color fieldname="" red="0" blue="0" green="0"/>
        <x fieldname=""/>
        <y fieldname=""/>
        <offset x="0" y="0" units="pt" yfieldname="" xfieldname=""/>
        <angle fieldname="" value="0" auto="0"/>
        <alignment fieldname="" value="center"/>
        <buffercolor fieldname="" red="255" blue="255" green="255"/>
        <buffersize fieldname="" units="pt" value="1"/>
        <bufferenabled fieldname="" on=""/>
        <multilineenabled fieldname="" on=""/>
        <selectedonly on=""/>
      </labelattributes>
      <editform></editform>
      <editforminit/>
      <featformsuppress>0</featformsuppress>
      <annotationform></annotationform>
      <editorlayout>generatedlayout</editorlayout>
      <excludeAttributesWMS/>
      <excludeAttributesWFS/>
      <attributeactions/>
      <edittypes>
        <edittype widgetv2type="TextEdit" name="cat">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
        <edittype widgetv2type="TextEdit" name="AREA">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
        <edittype widgetv2type="TextEdit" name="PERIMETER">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
        <edittype widgetv2type="TextEdit" name="PROVINCIA">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
        <edittype widgetv2type="TextEdit" name="ETTARI">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
        <edittype widgetv2type="TextEdit" name="area2">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
        <edittype widgetv2type="TextEdit" name="area_int">
          <widgetv2config IsMultiline="0" fieldEditable="1" UseHtml="0" labelOnTop="0"/>
        </edittype>
      </edittypes>
    </maplayer>
  </projectlayers>
  <properties>
    <WMSContactPerson type="QString"></WMSContactPerson>
    <WMSOnlineResource type="QString"></WMSOnlineResource>
    <WMSUseLayerIDs type="bool">false</WMSUseLayerIDs>
    <WMSContactOrganization type="QString"></WMSContactOrganization>
    <WMSKeywordList type="QStringList">
      <value></value>
    </WMSKeywordList>
    <WFSUrl type="QString"></WFSUrl>
    <Paths>
      <Absolute type="bool">false</Absolute>
    </Paths>
    <WMSServiceTitle type="QString"></WMSServiceTitle>
    <WFSLayers type="QStringList"/>
    <WMSContactMail type="QString"></WMSContactMail>
    <PositionPrecision>
      <DecimalPlaces type="int">2</DecimalPlaces>
      <Automatic type="bool">true</Automatic>
      <DegreeFormat type="QString">D</DegreeFormat>
    </PositionPrecision>
    <WCSUrl type="QString"></WCSUrl>
    <WMSServiceCapabilities type="bool">false</WMSServiceCapabilities>
    <WMSContactPhone type="QString"></WMSContactPhone>
    <WMSServiceAbstract type="QString"></WMSServiceAbstract>
    <WMSAddWktGeometry type="bool">false</WMSAddWktGeometry>
    <Measure>
      <Ellipsoid type="QString">intl</Ellipsoid>
    </Measure>
    <WMSPrecision type="QString">8</WMSPrecision>
    <WFSTLayers>
      <Insert type="QStringList"/>
      <Update type="QStringList"/>
      <Delete type="QStringList"/>
    </WFSTLayers>
    <Gui>
      <SelectionColorBluePart type="int">0</SelectionColorBluePart>
      <CanvasColorGreenPart type="int">255</CanvasColorGreenPart>
      <CanvasColorRedPart type="int">255</CanvasColorRedPart>
      <SelectionColorRedPart type="int">255</SelectionColorRedPart>
      <SelectionColorAlphaPart type="int">255</SelectionColorAlphaPart>
      <SelectionColorGreenPart type="int">255</SelectionColorGreenPart>
      <CanvasColorBluePart type="int">255</CanvasColorBluePart>
    </Gui>
    <Digitizing>
      <DefaultSnapToleranceUnit type="int">2</DefaultSnapToleranceUnit>
      <LayerSnappingList type="QStringList">
        <value>Province20150325102114484</value>
      </LayerSnappingList>
      <LayerSnappingEnabledList type="QStringList">
        <value>disabled</value>
      </LayerSnappingEnabledList>
      <SnappingMode type="QString">current_layer</SnappingMode>
      <AvoidIntersectionsList type="QStringList"/>
      <LayerSnappingToleranceUnitList type="QStringList">
        <value>2</value>
      </LayerSnappingToleranceUnitList>
      <LayerSnapToList type="QStringList">
        <value>to_vertex_and_segment</value>
      </LayerSnapToList>
      <DefaultSnapType type="QString">off</DefaultSnapType>
      <DefaultSnapTolerance type="double">0</DefaultSnapTolerance>
      <LayerSnappingToleranceList type="QStringList">
        <value>0.000000</value>
      </LayerSnappingToleranceList>
    </Digitizing>
    <Identify>
      <disabledLayers type="QStringList"/>
    </Identify>
    <Macros>
      <pythonCode type="QString"></pythonCode>
    </Macros>
    <WMSAccessConstraints type="QString"></WMSAccessConstraints>
    <WCSLayers type="QStringList"/>
    <Legend>
      <filterByMap type="bool">false</filterByMap>
    </Legend>
    <SpatialRefSys>
      <ProjectCRSProj4String type="QString">+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=1500000 +y_0=0 +ellps=intl +towgs84=-104.1,-49.1,-9.9,0.971,-2.917,0.714,-11.68 +units=m +no_defs</ProjectCRSProj4String>
      <ProjectCrs type="QString">EPSG:3003</ProjectCrs>
      <ProjectCRSID type="int">968</ProjectCRSID>
      <ProjectionsEnabled type="int">1</ProjectionsEnabled>
    </SpatialRefSys>
    <DefaultStyles>
      <Fill type="QString"></Fill>
      <Line type="QString"></Line>
      <Marker type="QString"></Marker>
      <RandomColors type="bool">true</RandomColors>
      <AlphaInt type="int">255</AlphaInt>
      <ColorRamp type="QString"></ColorRamp>
    </DefaultStyles>
    <WMSFees type="QString"></WMSFees>
    <WMSImageQuality type="int">90</WMSImageQuality>
    <WMSUrl type="QString"></WMSUrl>
  </properties>
</qgis>

**Comment by pcav** [comment]
sorry, no attachments in gh. may I send you the file privately?

**Comment by tomchadwin** [comment]
Issue confirmed and recreated. Looking at it now.

**Comment by tomchadwin** [comment]
@pcav, you've uncovered a fairly fundamental issue with how qgis2leaf extracts style information from layers. It assumes that polygon layers have fill styles, and does not handle the "Outline:simple line" style which your example uses. This will take some work to fix.

In the meantime, your workaround would be to change to a simple fill style with a transparent fill and the border style you need.

**Comment by pcav** [comment]
I see, thanks. Perhaps issue a warning, or at least document the issue, for now?
