### ISSUE TITLE
AttributeError: 'QgsLinePatternFillSymbolLayer' object has no attribute 'borderColor' error exporting layer poly vector with linear pattern style

### ISSUE THREAD

**Issue by marcobra** [Geolicious/qgis2leaf#217]
Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/qgis2leaf/qgis2leafdialog.py", line 297, in export2leaf
    qgis2leaf_exec(self.outFileName, self.basemapName, self.basemapMeta, self.basemapAddress, self.width, self.height, self.extent, self.full_screen, self.layer_list, self.visible, self.opacity, self.encode2JSON,self.createcluster, self.webpage_name, self.webmap_head,self.webmap_subhead, self.legend,self.locate,self.address, self.precision, self.labels, self.labelshover, self.matchCRS, self.selected)
  File "/home/ubuntu/.qgis2/python/plugins/qgis2leaf/qgis2leaf_exec.py", line 273, in qgis2leaf_exec
    borderColor_str = str(i.rendererV2().symbol().symbolLayer(0).borderColor().name())
AttributeError: 'QgsLinePatternFillSymbolLayer' object has no attribute 'borderColor'

Versione Python:
2.7.6 (default, Mar 22 2014, 23:03:41) 
[GCC 4.8.2]

Versione di QGIS:
2.8.1-Wien Wien, exported

Percorso Python: ['/home/ubuntu/.qgis2/python/plugins/GeoCoding', '/home/ubuntu/.qgis2/python/plugins/processing', '/usr/share/qgis/python', u'/home/ubuntu/.qgis2/python', u'/home/ubuntu/.qgis2/python/plugins', '/usr/share/qgis/python/plugins', '/usr/local/lib/python2.7/dist-packages/pip-1.5.6-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/csvkit-0.9.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/dbf-0.94.003-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/python_dateutil-2.2-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/six-1.8.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/openpyxl-2.1.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/SQLAlchemy-0.9.7-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/xlrd-0.9.3-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/jdcal-1.0-py2.7.egg', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gst-0.10', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client', '/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode', u'/home/ubuntu/.qgis2//python', '/home/ubuntu/.qgis2/python/plugins/SelectTools/tools', '/home/ubuntu/.qgis2/python/plugins/mmqgis/forms', '/home/ubuntu/.qgis2/python/plugins/DataDrivenInputMask', '/home/ubuntu/.qgis2/python/plugins/HouseNumbering/forms', '/home/ubuntu/.qgis2/python/plugins/StreamFeatureExtractor/third_party', '/home/ubuntu/.qgis2/python/plugins/QuickMultiAttributeEdit/forms', '/usr/share/qgis/python/plugins/fTools/tools', '/home/ubuntu/sister/estrazioni/cartografico/dati_cartografico_cxf_2014_12']

**Comment by tomchadwin** [comment]
Can you try changing from a pattern fill to a plain fill, and see if the error goes away?

**Comment by marcobra** [comment]
Yes, i know,  without linear pattern fill i get no error...

**Comment by tomchadwin** [comment]
In the short term, I'm not sure we can do much better than to trap the error properly. I don't know if Leaflet supports a pattern fill. If it does, we will have to extract the pattern into a web-friendly image format (which tiles, obviously).

Any ideas on how to pursue this one are gratefully received.

**Comment by tomchadwin** [comment]
If we trap the error, we can just substitute a plain fill.

**Comment by marcobra** [comment]
Will be nice to manage this error in some way.
Catch the error, show to user a warning, "The pattern fill conversion isn't supported, so layer: NAME_OF_LAYER pattern will be converted to plain fill" and then convert.
