### ISSUE TITLE
qgis2leaf development halted

### ISSUE THREAD

**Issue by tomchadwin** [Geolicious/qgis2leaf#269]
Hello all

After developing @riccardoklinger's qgis2leaf for nearly a year, I have now stopped. Instead, I have been working hard on https://github.com/tomchadwin/qgis2web. This plugin combines qgis2leaf with @volaya's qgis-ol3 plugin.

I am unlikely to continue work on qgis2leaf, as qgis2web is intended to do everything qgis2leaf does, and more. Please do take a look, and submit any issues you find.

Thanks

Tom

**Comment by epyks23** [comment]
I downloaded the qgis2web plugin and I try to open it but it freezes QGIS Desktop everytime

**Comment by epyks23** [comment]
I find that qgis2web is very fudgety and easily freezes. The more layers I have in QGIS, the more it freezes. Is there a way to go about this?

**Comment by tomchadwin** [comment]
Reduce the number or complexity of your layers. If qgis2web freezes, it's likely that a webpage would freeze.

**Comment by epyks23** [comment]
Unfortunately I cannot remove any layers as I need them in the map. Is there a similar plugin available?

**Comment by mtravis** [comment]
I do not think there are other similar plugins. This one makes simple web maps very well. 

If you can't remove layers try removing fields from them that you don't need. You can also open the geojson files and edit them to reduce the amount of characters used for the coords. 

Out of interest how big is your data folder?

**Comment by epyks23** [comment]
My data is at about 2.76323 GB so far, and it will increase

**Comment by tomchadwin** [comment]
I'm no expert, but that sounds like several orders of magnitude more vector data than a webmap can normally handle. I would look at other approaches,  such as rasterizing and then tiling your data.

**Comment by epyks23** [comment]
I am using Geoserver and it does not seem to have a problem with the size of the shapefile. The only issue I have is making a legend for it because there are so many layers that the user would need a legend to turn them on and off.

**Comment by tomchadwin** [comment]
Ah, so you are not JSON-encoding the layers? OK. So would the legend issue be solved if you could select which layers were represented in the legend? If not, what visual solution do you imagine which qgis2web cannot yet produce?

**Comment by epyks23** [comment]
I am not sure what you are asking. qgis2web would be perfect because it automatically makes a legend if I choose to. But since my data is very large, I could not use QGIS2Web (when I opened the HTML file, the map does not show up.. it says there is an error with the webpage). My layers are shapefiles

But yes, I would need a legend on my Geoserver map because it's a bit chaotic at the moment with all the layers turned on. I would want the user to turn layers on and off.

**Comment by tomchadwin** [comment]
When the map fails to open in the browser, and you get the error, could you open the browser console (F12 on Windows) and paste any errors you see there when you refresh? Unchecking "Visible" for a lot of the layers might allow the page to load. I'm just not sure how a legend can display on screen if you have so many layers. Edit the output code to make the legend scrollable, I guess.

**Comment by epyks23** [comment]
I opened the browser console and refreshed it and I get the following:

![image](https://cloud.githubusercontent.com/assets/16273641/12004342/1d7ba776-ab20-11e5-9f56-cb7355066dfe.png)

**Comment by epyks23** [comment]
![image](https://cloud.githubusercontent.com/assets/16273641/12004346/5f17d5ce-ab20-11e5-94be-0550bb4546c4.png)

**Comment by tomchadwin** [comment]
Can you click on the "Console" tab,  next to "Elements", which is what your screenshot shows?

**Comment by epyks23** [comment]
![image](https://cloud.githubusercontent.com/assets/16273641/12004448/d373bf44-ab27-11e5-90e0-02ef7945ab00.png)

**Comment by epyks23** [comment]
Quick question -- Is it possible to export a raster in the plugin?

**Comment by tomchadwin** [comment]
Yes, but the feature had not been used very much, so you might come across problems. Report them if you do. From memory, avoid using "Match project CRS" with rasters.

**Comment by epyks23** [comment]
I avoided "Match project CRS". When I open the plugin, this message comes up:

qgis2web produced an error:

Traceback (most recent call last):
File "C:/Users/EninnaL/.qgis2/python/plugins\qgis2web\maindialog.py", line 113, in previewMap
MainDialog.previewOL3(self)
File "C:/Users/EninnaL/.qgis2/python/plugins\qgis2web\maindialog.py", line 281, in previewOL3
cluster, params, utils.tempFolder())
File "C:/Users/EninnaL/.qgis2/python/plugins\qgis2web\olwriter.py", line 63, in writeOL
settings, json, matchCRS, clustered)
File "C:/Users/EninnaL/.qgis2/python/plugins\qgis2web\olwriter.py", line 482, in writeLayersAndGroups
matchCRS, cluster)])
File "C:/Users/EninnaL/.qgis2/python/plugins\qgis2web\olwriter.py", line 583, in layerToJavascript
renderer = layer.rendererV2()
AttributeError: 'QgsRasterLayer' object has no attribute 'rendererV2'

When I click on Export, This message comes up:

An error has occured while executing Python code:
Traceback (most recent call last):
  File "C:/Users/<user>/.qgis2/python/plugins\qgis2web\maindialog.py", line 128, in saveMap
    MainDialog.saveOL(self)
  File "C:/Users/<user>/.qgis2/python/plugins\qgis2web\maindialog.py", line 301, in saveOL
    json, cluster, params, folder)
  File "C:/Users/<user>/.qgis2/python/plugins\qgis2web\olwriter.py", line 63, in writeOL
    settings, json, matchCRS, clustered)
  File "C:/Users/<user>/.qgis2/python/plugins\qgis2web\olwriter.py", line 482, in writeLayersAndGroups
    matchCRS, cluster)])
  File "C:/Users/<user>/.qgis2/python/plugins\qgis2web\olwriter.py", line 583, in layerToJavascript
    renderer = layer.rendererV2()
AttributeError: 'QgsRasterLayer' object has no attribute 'rendererV2'

**Comment by tomchadwin** [comment]
I'll take a look at this on 4 January. I'm not at a machine before then.

**Comment by tomchadwin** [comment]
I've logged this issue at https://github.com/tomchadwin/qgis2web/issues/159 - follow it there.

**Comment by tomchadwin** [comment]
This has been fixed and released in 1.0.0-RC2 from the QGIS plugins repo.
