### ISSUE TITLE
not compatible with Python 2.6 (Mac OS X 10.6)

### ISSUE THREAD

**Issue by cbertelli** [Geolicious/qgis2leaf#271]
Impossibile caricare il plugin qgis2leaf a causa di un errore chiamando il metodo classFactory()

Traceback (most recent call last):
  File "/Applications/QGIS_2.9-dev_SnoLeo_20150531.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/carlo/.qgis2/python/plugins/qgis2leaf/**init**.py", line 50, in classFactory
    from qgis2leaf import qgis2leaf
  File "/Applications/QGIS_2.9-dev_SnoLeo_20150531.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carlo/.qgis2/python/plugins/qgis2leaf/qgis2leaf.py", line 29, in 
    from qgis2leafdialog import qgis2leafDialog
  File "/Applications/QGIS_2.9-dev_SnoLeo_20150531.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carlo/.qgis2/python/plugins/qgis2leaf/qgis2leafdialog.py", line 27, in 
    from qgis2leaf_exec import qgis2leaf_exec
  File "/Applications/QGIS_2.9-dev_SnoLeo_20150531.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carlo/.qgis2/python/plugins/qgis2leaf/qgis2leaf_exec.py", line 27, in 
    import processing
  File "/Applications/QGIS_2.9-dev_SnoLeo_20150531.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carlo/.qgis2/python/plugins/processing/__init__.py", line 29, in 
    from processing.tools.general import *
  File "/Applications/QGIS_2.9-dev_SnoLeo_20150531.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carlo/.qgis2/python/plugins/processing/tools/general.py", line 28, in 
    from processing.core.Processing import Processing
  File "/Applications/QGIS_2.9-dev_SnoLeo_20150531.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carlo/.qgis2/python/plugins/processing/core/Processing.py", line 46, in 
    from processing.modeler.ModelerAlgorithmProvider import ModelerAlgorithmProvider
  File "/Applications/QGIS_2.9-dev_SnoLeo_20150531.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carlo/.qgis2/python/plugins/processing/modeler/ModelerAlgorithmProvider.py", line 36, in 
    from processing.modeler.ModelerAlgorithm import ModelerAlgorithm
  File "/Applications/QGIS_2.9-dev_SnoLeo_20150531.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/carlo/.qgis2/python/plugins/processing/modeler/ModelerAlgorithm.py", line 100
    return {k:v for k,v in self.__dict__.iteritems() if not k.startswith("_")}
                  ^
SyntaxError: invalid syntax

Versione Python:
2.6.1 (r261:67515, Jun 24 2010, 21:47:49) 
[GCC 4.2.1 (Apple Inc. build 5646)]

Versione di QGIS:
2.9.0-Master Master, 56620e2

Percorso Python: ['/Users/carlo/.qgis2/python/plugins/GeoCoding/libs', '/Applications/QGIS_2.9-dev_SnoLeo_20150531.app/Contents/MacOS/../Resources/python', u'/Users/carlo/.qgis2/python', u'/Users/carlo/.qgis2/python/plugins', '/Applications/QGIS_2.9-dev_SnoLeo_20150531.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/B/Python/2.6', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.6', '/Library/Python/2.6/site-packages/numpy-override', '/Library/Frameworks/GDAL.framework/Versions/1.10/Python/2.6/site-packages', '/Library/Python/2.6/site-packages/Shapely-1.2.17-py2.6.egg', '/Library/Python/2.6/site-packages/Pygments-1.6-py2.6.egg', '/Library/Python/2.6/site-packages/SQLAlchemy-0.8.2-py2.6-macosx-10.6-universal.egg', '/Library/Python/2.6/site-packages/importlib-1.0.2-py2.6.egg', '/Library/Python/2.6/site-packages/pip-1.5.4-py2.6.egg', '/Library/Python/2.6/site-packages/pykml-0.1.0-py2.6.egg', '/Library/Python/2.6/site-packages/lxml-3.3.2-py2.6-macosx-10.6-universal.egg', '/Library/Python/2.6/site-packages/argparse-1.2.1-py2.6.egg', '/Library/Python/2.6/site-packages/geojsonio-0.0.1-py2.6.egg', '/Library/Python/2.6/site-packages/github3.py-0.9.0-py2.6.egg', '/Library/Python/2.6/site-packages/uritemplate.py-0.3.0-py2.6.egg', '/Library/Python/2.6/site-packages/requests-2.3.0-py2.6.egg', '/Library/Python/2.6/site-packages/rdflib-4.1.2-py2.6.egg', '/Library/Python/2.6/site-packages/html5lib-1.0b3-py2.6.egg', '/Library/Python/2.6/site-packages/ordereddict-1.1-py2.6.egg', '/Library/Python/2.6/site-packages/SPARQLWrapper-1.6.2-py2.6.egg', '/Library/Python/2.6/site-packages/pyparsing-2.0.2-py2.6.egg', '/Library/Python/2.6/site-packages/isodate-0.5.0-py2.6.egg', '/Library/Python/2.6/site-packages/six-1.7.3-py2.6.egg', '/Library/Python/2.6/site-packages/OWSLib-0.8.8-py2.6.egg', '/Library/Python/2.6/site-packages/pytz-2014.4-py2.6.egg', '/Library/Python/2.6/site-packages/python_dateutil-2.2-py2.6.egg', '/Library/Python/2.6/site-packages/numpy-1.8.2-py2.6-macosx-10.6-universal.egg', '/Library/Python/2.6/site-packages/matplotlib-1.4.0-py2.6-macosx-10.6-universal.egg', '/Library/Python/2.6/site-packages/mock-1.0.1-py2.6.egg', '/Library/Python/2.6/site-packages/nose-1.3.4-py2.6.egg', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python26.zip', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/lib-dynload', '/Library/Python/2.6/site-packages', '/Library/Python/2.6/site-packages/PIL', '/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/PyObjC', '/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/wx-2.8-mac-unicode', u'/Users/carlo/.qgis2//python', '/Users/carlo/.qgis2/python/plugins/DataDrivenInputMask', '/Users/carlo/.qgis2/python/plugins/GeneticSimplifier', '/Users/carlo/.qgis2/python/plugins/mmqgis/forms', '/Users/carlo/.qgis2/python/plugins/QuickMultiAttributeEdit/forms', '/Applications/QGIS_2.9-dev_SnoLeo_20150531.app/Contents/Resources/python/plugins/fTools/tools', '/Users/carlo/.qgis2/python/plugins/DigitizingTools/tools', '.']

**Comment by tomchadwin** [comment]
Labelled as invalid and closed because it is an issue with processing, not qgis2web
