### ISSUE TITLE
AttributeError: 'QgsFillSymbolV2' object has no attribute 'size'

### ISSUE THREAD

**Issue by nothing-butanol** [Geolicious/qgis2leaf#272]
Hi, I have been having an issue with point data being displayed using categorized styling. I keep receiving the error below. Single symbol is fine for the data. Maybe I'm doing something wrong.

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/Users/--------------/.qgis2/python/plugins\qgis2leaf\qgis2leafdialog.py", line 297, in export2leaf
    qgis2leaf_exec(self.outFileName, self.basemapName, self.basemapMeta, self.basemapAddress, self.width, self.height, self.extent, self.full_screen, self.layer_list, self.visible, self.opacity, self.encode2JSON,self.createcluster, self.webpage_name, self.webmap_head,self.webmap_subhead, self.legend,self.locate,self.address, self.precision, self.labels, self.labelshover, self.matchCRS, self.selected)
  File "C:/Users/------------/.qgis2/python/plugins\qgis2leaf\qgis2leaf_exec.py", line 519, in qgis2leaf_exec
    fillOpacity: '""" + str(symbol.alpha()) + """',
AttributeError: 'QgsFillSymbolV2' object has no attribute 'size'

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.8.2-Wien Wien, 1b929ef

**Comment by tomchadwin** [comment]
Can you try qgis2web and see if that works? qgis2leaf has not had any development for a little while now.

**Comment by nothing-butanol** [comment]
Thank you. It does work with qgis2web. I was unaware it existed. It did have an issue showing all the categories of my point data with openmap3, but worked well with leaflet. Thanks again for all your work.
