### ISSUE TITLE
Issue with using "Layer Extent"

### ISSUE THREAD

**Issue by HeikkiVesanto** [Geolicious/qgis2leaf#273]
Thanks for the Plugin, excellent work! Looks great overall.

With a EPSG:3857 project. When using the canvas extent it works great.

Slight issue, I get the following when choosing:
Extent: Use Layer Extent

An error has occured while executing Python code:

Traceback (most recent call last):
  File "C:/Users/tseepra/.qgis2/python/plugins\qgis2leaf\qgis2leafdialog.py", line 297, in export2leaf
    qgis2leaf_exec(self.outFileName, self.basemapName, self.basemapMeta, self.basemapAddress, self.width, self.height, self.extent, self.full_screen, self.layer_list, self.visible, self.opacity, self.encode2JSON,self.createcluster, self.webpage_name, self.webmap_head,self.webmap_subhead, self.legend,self.locate,self.address, self.precision, self.labels, self.labelshover, self.matchCRS, self.selected)
  File "C:/Users/tseepra/.qgis2/python/plugins\qgis2leaf\qgis2leaf_exec.py", line 290, in qgis2leaf_exec
    print '>> ' + crsProj4
UnboundLocalError: local variable 'crsProj4' referenced before assignment

Python version:
2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)]

QGIS version:
2.10.1-Pisa Pisa, d20c5b7

Python path: ['C:/OSGEO4~1/apps/qgis/./python/plugins\processing', 'C:/OSGEO4~1/apps/qgis/./python', u'C:/Users/tseepra/.qgis2/python', u'C:/Users/tseepra/.qgis2/python/plugins', 'C:/OSGEO4~1/apps/qgis/./python/plugins', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\matplotlib-1.3.1-py2.7-win-amd64.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\nose-1.3.3-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\tornado-4.0.1-py2.7-win-amd64.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\backports.ssl_match_hostname-3.4.0.2-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\certifi-14.05.14-py2.7.egg', 'c:\osgeo4~1\apps\python27\lib\site-packages\python_dateutil-2.1-py2.7.egg', 'c:\osgeo4~1\apps\python27\lib\site-packages\six-1.3.0-py2.7.egg', 'C:\OSGEO4~1\bin\python27.zip', 'C:\OSGEO4~1\apps\Python27\DLLs', 'C:\OSGEO4~1\apps\Python27\lib', 'C:\OSGEO4~1\apps\Python27\lib\plat-win', 'C:\OSGEO4~1\apps\Python27\lib\lib-tk', 'C:\OSGEO4~1\bin', 'C:\OSGEO4~1\apps\Python27', 'C:\OSGEO4~1\apps\Python27\lib\site-packages', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\PIL', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\pytz-2012j-py2.7.egg', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\win32', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\win32\lib', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\Pythonwin', 'C:\OSGEO4~1\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'C:/Users/tseepra/.qgis2//python', 'C:\OSGEO4~1\apps\qgis\python\plugins\fTools\tools']

**Comment by tomchadwin** [comment]
Try qgis2web - I think this issue might have been fixed.
